In [1]:
import pandas as pd
import numpy as np

In [2]:
products = pd.read_csv('products.csv')

In [3]:
products.head()

,product_id,product_name,category,sub_category,unit_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64

In [4]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     612 non-null    str
 1   product_name   612 non-null    str
 2   category       602 non-null    str
 3   sub_category   612 non-null    str
 4   unit_price     594 non-null    float64
 5   unit_cost      612 non-null    float64
 6   seller_id      612 non-null    str
 7   quality_score  612 non-null    float64
dtypes: float64(3), str(5)
memory usage: 69.4 KB

In [5]:
df_pr = products.copy()

In [6]:
df_pr.info()

<class 'pandas.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     612 non-null    str
 1   product_name   612 non-null    str
 2   category       602 non-null    str
 3   sub_category   612 non-null    str
 4   unit_price     594 non-null    float64
 5   unit_cost      612 non-null    float64
 6   seller_id      612 non-null    str
 7   quality_score  612 non-null    float64
dtypes: float64(3), str(5)
memory usage: 69.4 KB

In [7]:
df_pr.head()

,product_id,product_name,category,sub_category,unit_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64

In [9]:
df_pr.duplicated().sum()

np.int64(12)

In [11]:
df_pr = df_pr.drop_duplicates()

In [12]:
df_pr.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 611
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     600 non-null    str
 1   product_name   600 non-null    str
 2   category       590 non-null    str
 3   sub_category   600 non-null    str
 4   unit_price     584 non-null    float64
 5   unit_cost      600 non-null    float64
 6   seller_id      600 non-null    str
 7   quality_score  600 non-null    float64
dtypes: float64(3), str(5)
memory usage: 72.9 KB

In [13]:
df_pr['product_name'].unique()

<ArrowStringArray>
[         'Books Item 494',    'Electronics Item 473',
         'Sports Item 108', 'Home & Kitchen Item 559',
        'Fashion Item 536',        'Fashion Item 384',
        'Grocery Item 174', 'Home & Kitchen Item 492',
        'Fashion Item 435',         'Beauty Item 395',
 ...
    'Electronics Item 277', 'Home & Kitchen Item 179',
          'Books Item 282',    'Electronics Item 391',
           'Toys Item 509',          'Books Item 584',
         'Beauty Item 145',         'Fashion Item 73',
           'Toys Item 236',            'Toys Item 38']
Length: 600, dtype: str

In [14]:
df_pr['category'].unique()

<ArrowStringArray>
[           'Books',       'Electronic',           'Sports',
   'Home & Kitchen',          'Fashion',          'Grocery',
           'Beauty',    ' Electronics ',      'ELECTRONICS',
                nan,             'Toys', ' Home & Kitchen ',
          'FASHION',         ' Sports ',          ' Books ',
   'HOME & KITCHEN',        ' Fashion ',      'Electronics',
           'BEAUTY',              'NAN',             'TOYS',
           'SPORTS',            'BOOKS',          'GROCERY',
         ' Beauty ',           ' Toys ',        ' Grocery ']
Length: 27, dtype: str

In [16]:
df_pr['category'] = df_pr['category'].astype(str).str.strip().str.title()

In [17]:
df_pr['category'].unique()

<ArrowStringArray>
[         'Books',     'Electronic',         'Sports', 'Home & Kitchen',
        'Fashion',        'Grocery',         'Beauty',    'Electronics',
              nan,           'Toys',            'Nan']
Length: 11, dtype: str

In [19]:
df_pr['category'] = df_pr['category'].replace({'Nan':np.nan})

In [20]:
df_pr['category'].unique()

<ArrowStringArray>
[         'Books',     'Electronic',         'Sports', 'Home & Kitchen',
        'Fashion',        'Grocery',         'Beauty',    'Electronics',
              nan,           'Toys']
Length: 10, dtype: str

In [21]:
df_pr['sub_category'].unique()

<ArrowStringArray>
[         'Books - Type 2',    'Electronics - Type 3',
         'Sports - Type 2', 'Home & Kitchen - Type 2',
        'Fashion - Type 1',        'Fashion - Type 4',
        'Grocery - Type 1',        'Fashion - Type 2',
         'Beauty - Type 2',        'Grocery - Type 4',
         'Sports - Type 4', 'Home & Kitchen - Type 1',
          'Books - Type 1',    'Electronics - Type 1',
         'Beauty - Type 4',         'Sports - Type 1',
    'Electronics - Type 4',    'Electronics - Type 2',
 'Home & Kitchen - Type 4',           'Toys - Type 4',
         'Beauty - Type 3',          'Books - Type 4',
         'Sports - Type 3',        'Fashion - Type 3',
 'Home & Kitchen - Type 3',           'Toys - Type 3',
           'Toys - Type 1',         'Beauty - Type 1',
           'Toys - Type 2',          'Books - Type 3',
        'Grocery - Type 2',        'Grocery - Type 3']
Length: 32, dtype: str

In [22]:
# we can fill category by using sub_category

In [32]:
df_pr['category'] = df_pr['category'].astype(str).fillna(df_pr['sub_category']).str.strip('-')

In [35]:
df_pr['category'].unique()

<ArrowStringArray>
[               'Books',           'Electronic',               'Sports',
       'Home & Kitchen',              'Fashion',              'Grocery',
               'Beauty',          'Electronics',      'Beauty - Type 4',
                 'Toys',       'Books - Type 1',      'Beauty - Type 2',
        'Toys - Type 4',      'Sports - Type 2',      'Sports - Type 3',
       'Books - Type 4', 'Electronics - Type 2',     'Fashion - Type 4',
       'Books - Type 3']
Length: 19, dtype: str

In [38]:
wrong_rows = df_pr[df_pr['category'] == df_pr['sub_category']]

In [40]:
wrong_rows

,product_id,product_name,category,sub_category,unit_price,unit_cost,seller_id,quality_score
27,P0149,Beauty Item 149,Beauty - Type 4,Beauty - Type 4,249.90,181.15,S0100,3.17
172,P0350,Books Item 350,Books - Type 1,Books - Type 1,423.13,272.48,S0047,2.61
193,P0268,Beauty Item 268,Beauty - Type 2,Beauty - Type 2,522.56,240.91,S0149,4.38
207,P0053,Toys Item 53,Toys - Type 4,Toys - Type 4,320.30,195.39,S0134,3.26
250,P0520,Sports Item 520,Sports - Type 2,Sports - Type 2,4762.61,351747.00,S0198,4.20
273,P0437,Beauty Item 437,Beauty - Type 2,Beauty - Type 2,740.24,420.04,S0160,3.03
321,P0599,Sports Item 599,Sports - Type 3,Sports - Type 3,405.05,313.72,S0026,4.76
325,P0015,Books Item 15,Books - Type 4,Books - Type 4,334.20,267.23,S0103,2.51
419,P0288,Electronics Item 288,Electronics - Type 2,Electronics - Type 2,3472.61,2669.94,S0005,3.00
472,P0468,Fashion Item 468,Fashion - Type 4,Fashion - Type 4,3191.57,1325.79,S0091,2.67
508,P0355,Books Item 355,Books - Type 3,Books - Type 3,539.11,440.57,S0129,3.97
564,P0467,Toys Item 467,Toys - Type 4,Toys - Type 4,290.26,198.40,S0076,3.79

In [42]:
df_pr.loc[wrong_rows.index, 'category'] = (df_pr.loc[wrong_rows.index, 'sub_category'].str.split('-').str[0].str.strip())

In [44]:
# that was a mistake above we fixed in above row

In [43]:
df_pr['category'].unique()

<ArrowStringArray>
[         'Books',     'Electronic',         'Sports', 'Home & Kitchen',
        'Fashion',        'Grocery',         'Beauty',    'Electronics',
           'Toys']
Length: 9, dtype: str

In [45]:
df_pr.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 611
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     600 non-null    str
 1   product_name   600 non-null    str
 2   category       600 non-null    str
 3   sub_category   600 non-null    str
 4   unit_price     584 non-null    float64
 5   unit_cost      600 non-null    float64
 6   seller_id      600 non-null    str
 7   quality_score  600 non-null    float64
dtypes: float64(3), str(5)
memory usage: 89.0 KB

In [46]:
df_pr['unit_price'].unique()

array([ 2.422500e+02,  4.026160e+03,  4.814500e+03,  6.204230e+03,
        1.291230e+03,  3.164180e+03,  2.056900e+02,  3.153560e+03,
        4.333700e+02,  3.432900e+02,  4.522220e+03,  7.569200e+02,
        3.726750e+03,  1.938870e+03,  1.922900e+02,  1.548042e+04,
        1.190800e+02,  2.577310e+03,  3.020200e+02,  1.593620e+03,
        1.725650e+03,  1.076920e+03,  1.999595e+04,  5.687500e+02,
        6.524280e+03,  5.495184e+04,  2.627210e+03,  2.499000e+02,
        7.342000e+02,  4.305210e+03,  4.215565e+04,  6.444700e+02,
        4.251600e+02,  3.495830e+03,  2.814000e+03,  3.130340e+03,
        3.475700e+02,  4.876060e+03,  4.142490e+03,  7.671200e+02,
        7.886210e+03,  1.159775e+04,  4.236870e+03,  1.452353e+04,
        2.344030e+03,  1.857200e+03,  4.667400e+02,  6.486000e+01,
        2.104780e+03,  5.597000e+02,  1.141900e+02,  2.196340e+03,
                 nan,  2.079200e+02,  1.441310e+03,  2.306920e+03,
       -2.525450e+03,  1.159014e+04,  2.886301e+04,  1.888840e+03,
        5.835400e+02,  8.466600e+02,  5.155300e+02,  7.252300e+02,
        2.967980e+03,  8.049400e+02,  5.458300e+02,  8.289800e+02,
       -6.357300e+02,  2.888700e+03,  4.823900e+02,  3.707600e+02,
        3.115200e+02,  5.026800e+02,  2.004090e+03, -1.067950e+03,
        1.423630e+03,  5.507880e+03,  8.205300e+02,  4.661269e+04,
        3.831500e+03,  3.277100e+02,  2.439500e+02,  2.627133e+04,
        2.373000e+02,  3.618100e+02,  1.553500e+02,  3.760630e+03,
        9.031700e+02,  4.802400e+02,  1.305739e+04,  1.894500e+02,
        3.996700e+02,  3.228420e+03,  7.137800e+02,  7.033270e+03,
        2.535200e+02,  3.611390e+03,  4.447300e+02,  4.361800e+02,
        1.179162e+04,  5.834250e+03,  3.851800e+02,  1.454590e+03,
       -1.979970e+03,  1.352370e+03,  6.077000e+02,  3.136900e+03,
        1.028780e+03,  5.366790e+03,  8.044240e+03,  8.243600e+02,
        3.742200e+02,  3.616600e+02,  4.875600e+02,  7.894500e+03,
        9.218420e+03,  5.640000e+01,  2.606100e+02,  1.917540e+03,
        2.079720e+04,  2.034600e+02,  3.186600e+02,  3.916140e+03,
        4.042712e+04,  2.670690e+03,  4.259700e+02,  1.544600e+03,
        1.652910e+03,  1.022255e+04,  1.261960e+04,  4.072160e+03,
        6.509500e+02,  1.985600e+02,  1.258300e+02,  7.440270e+03,
        3.043550e+03,  1.460024e+04,  9.333400e+02,  2.591700e+02,
        1.436900e+03,  1.059000e+02,  6.299700e+02,  6.923000e+02,
        1.760480e+03,  4.756550e+03,  1.842055e+04,  9.395250e+03,
        3.682000e+03,  1.909360e+03,  1.942265e+04,  1.427240e+04,
        1.947400e+02,  1.893060e+03,  2.138000e+02,  3.397800e+02,
        5.197160e+03,  4.186100e+02,  4.717180e+03,  7.266270e+03,
        4.631800e+02,  7.707900e+02,  5.330500e+02,  9.816100e+02,
        2.550200e+02,  1.443200e+02,  1.242090e+03,  4.231300e+02,
        1.309970e+03,  3.664600e+02,  3.686000e+02,  2.777200e+02,
        2.069360e+03,  1.299960e+03,  5.256000e+02,  1.285410e+03,
        1.298250e+03,  3.298130e+03,  5.128000e+02,  2.222700e+02,
       -6.334200e+02,  1.564925e+04,  2.166061e+04,  5.461600e+02,
        1.046563e+04,  4.483310e+03,  1.869640e+03,  5.225600e+02,
        6.659290e+03,  6.948900e+02,  1.137360e+03,  1.327830e+03,
        2.958789e+04,  2.560560e+03,  5.406240e+03,  3.144200e+02,
        3.659100e+02,  4.992660e+03,  2.403478e+04,  8.780900e+02,
        3.203000e+02,  6.308500e+02,  4.958762e+04,  3.749200e+02,
        9.838360e+03,  6.930500e+02,  6.520900e+02,  2.764800e+02,
        3.159500e+02,  2.620961e+04,  1.755850e+03,  3.281400e+02,
        3.393260e+03,  2.932540e+03,  7.342100e+03,  5.237213e+04,
       -4.930538e+04,  3.949142e+04,  3.575870e+03,  8.980200e+02,
        9.536200e+02,  1.259871e+04,  1.648440e+03,  4.896700e+02,
        1.084066e+04,  3.912000e+02,  5.724300e+02,  1.771000e+03,
        1.191930e+03,  4.845990e+03,  4.413800e+02,  6.906200e+02,
        4.663150e+03,  6.232300e+02,  2.807000e+02,  2.398340e+03,
        3.726040e+03,  7.404400e+02,  5.475700e+02,  1.953700e+02,
        1.403300e+02,  6.107460e+03,  4.762610e+03,  4.041130e+03,
        4.414860e+03,  3.727000e+02,  2.306270e+03,  1.286950e+03,
        4.894900e+02,  2.392280e+03,  5.607000e+02,  2.770600e+02,
        1.215120e+03,  1.516160e+03,  1.601790e+03,  1.716600e+02,
        8.754100e+02,  9.039000e+02,  5.494800e+02,  4.269200e+02,
        8.326260e+03,  2.112810e+03,  4.580000e+02, -8.978200e+02,
       -5.443810e+03,  7.402400e+02,  6.031500e+02,  7.477700e+02,
        4.384410e+03,  1.234046e+04,  3.185930e+03,  1.405250e+03,
        1.085540e+03,  6.246000e+02,  2.648920e+03,  2.081500e+02,
        1.318970e+03,  2.627360e+03,  2.597720e+03,  7.057900e+02,
        3.025930e+03,  1.603700e+02,  1.107860e+03,  1.454470e+03,
        9.747870e+03,  4.410800e+02,  3.828310e+03,  1.716249e+04,
        1.165410e+03,  1.151520e+03,  1.490770e+03,  8.700300e+02,
        2.519750e+03,  1.660700e+02,  1.530860e+03,  2.441660e+03,
        3.708500e+02, -1.000000e+02,  3.312100e+02,  2.076800e+03,
        2.605710e+03,  2.003700e+02,  8.682600e+02,  2.583900e+02,
        2.706930e+03,  3.695500e+02,  8.592350e+03,  3.843640e+03,
        1.413600e+03,  4.050500e+02,  8.628000e+01,  7.708700e+02,
        3.342000e+02,  4.627131e+04,  2.411908e+04,  2.059200e+02,
        1.178650e+03,  1.351010e+03,  5.765500e+02,  4.729300e+02,
        4.080400e+02,  3.626400e+02,  1.769400e+02,  6.844740e+03,
        3.178700e+02,  1.902790e+03,  9.415000e+02,  1.029560e+03,
        5.982500e+02, -2.983410e+03,  3.511359e+04,  6.954000e+01,
        4.515600e+02,  1.194254e+04,  5.730040e+03,  7.243600e+02,
        6.554570e+03,  6.825300e+02,  4.557900e+02,  1.719220e+03,
        6.817840e+03,  3.250500e+02,  9.309700e+03,  6.268440e+03,
        1.657170e+03,  9.382200e+02,  4.154813e+04,  1.696350e+03,
        2.269570e+03,  1.080020e+03,  1.010984e+04,  3.212400e+02,
        2.711800e+02,  1.223930e+03,  1.712175e+04,  8.371100e+02,
        4.845200e+02,  1.229100e+03,  1.205539e+04,  6.446680e+03,
        5.944680e+03,  7.114600e+02,  1.674990e+03,  2.979440e+03,
        6.856300e+02,  4.769400e+02,  1.942500e+02,  3.571510e+03,
        5.183200e+02,  7.943900e+02,  1.563920e+03,  9.801650e+03,
        4.069500e+02,  2.459850e+03,  2.195110e+03,  6.639600e+02,
        8.288600e+02,  3.091900e+02,  4.814500e+02,  3.878200e+02,
        1.271890e+03,  2.956990e+03,  3.415320e+03,  1.612700e+02,
        1.029400e+02,  2.522200e+02,  2.893232e+04,  3.433300e+02,
        1.268925e+04,  1.124920e+03, -1.384398e+04,  6.424500e+02,
        1.940900e+02,  5.745400e+02,  4.781500e+02,  1.845330e+03,
        3.385680e+03,  2.892260e+03,  5.179500e+02,  3.444300e+02,
        9.156500e+02,  5.660230e+03,  1.727520e+03,  5.451000e+02,
        3.472610e+03,  3.582610e+03,  4.205400e+02,  7.821600e+02,
        2.653700e+02,  1.014440e+03,  2.488050e+03,  7.810300e+02,
        9.156200e+02,  2.233480e+03,  3.242460e+03,  2.257900e+02,
        4.016060e+03,  3.296100e+02,  4.830700e+02,  7.937600e+02,
        1.289370e+03,  7.967800e+02,  5.454400e+02,  1.378970e+03,
        4.279100e+02,  1.660400e+02,  6.556780e+03,  7.355000e+02,
        9.788920e+03,  5.257000e+02,  3.994300e+02,  5.907900e+02,
        1.509036e+04,  1.876680e+03,  2.638260e+03,  3.005140e+03,
        1.650990e+03,  4.876800e+02,  5.396500e+02,  1.233300e+02,
        2.955701e+04,  1.674640e+03,  1.206500e+02,  1.587080e+03,
        4.085700e+02,  4.566800e+03,  3.775400e+03,  8.106300e+02,
        4.625380e+03,  3.763210e+03,  5.708600e+02,  5.991580e+03,
        2.129451e+04,  1.097430e+03,  4.175170e+03,  3.191570e+03,
        8.751700e+02,  5.182600e+02,  1.537500e+03,  4.769700e+02,
        8.418900e+02,  3.527800e+03,  1.517130e+03,  5.755800e+02,
        3.577110e+03,  3.360411e+04,  4.671200e+02,  2.534720e+03,
        1.160560e+03,  2.359450e+03,  1.787490e+03,  4.730728e+04,
        3.347330e+03,  1.011370e+03,  4.383000e+02,  4.450970e+03,
        8.452600e+02,  4.978192e+04,  3.082450e+03,  2.175673e+04,
        3.181300e+02,  1.873000e+02,  5.091000e+01,  4.136600e+02,
        1.561340e+03,  9.812400e+02,  6.327300e+03,  1.111040e+03,
        1.339132e+04,  5.391100e+02,  1.841180e+03,  4.392100e+02,
        1.483500e+03,  6.447800e+02,  3.252200e+03,  8.382200e+02,
        3.099700e+02,  2.595100e+02,  8.564700e+02,  2.121494e+04,
        1.510270e+03,  3.622200e+02,  9.747590e+03,  7.222500e+02,
        2.418730e+03,  4.540900e+02,  1.452130e+04,  3.665660e+03,
        7.886000e+01,  7.646680e+03,  4.511200e+02,  4.506810e+03,
        5.765430e+03,  5.110345e+04,  2.130600e+02,  1.483070e+03,
        5.118600e+02,  2.676970e+03,  3.554970e+03,  2.993900e+02,
        3.894900e+02,  8.219470e+03,  7.729100e+02,  5.414600e+02,
        3.417100e+02,  1.469720e+03,  7.664300e+02,  2.789500e+02,
        3.200420e+03,  6.225960e+03,  1.647850e+04,  6.182300e+02,
        1.403520e+03,  5.039200e+02,  5.441700e+02,  1.997500e+02,
        4.861149e+04,  7.036800e+02,  2.178500e+02,  5.742500e+02,
        3.639660e+03,  4.599540e+03,  2.902600e+02,  3.679730e+03,
        1.711910e+03,  5.918400e+02,  3.561132e+04,  1.492074e+04,
        2.374980e+04,  9.902100e+02,  3.763290e+03,  4.278550e+03,
        4.741880e+03,  4.491600e+02,  3.719700e+03,  3.419670e+03,
        6.563200e+02,  1.625240e+03,  2.860540e+03,  3.546210e+03,
        3.070100e+02,  2.188840e+03,  3.207700e+02,  1.720930e+03,
        3.099500e+02,  7.377600e+02,  1.181050e+03,  4.898000e+02,
        6.240860e+03,  6.006200e+02,  1.068790e+03,  1.760500e+03,
        1.060700e+02,  1.481200e+02,  2.075350e+03,  1.146310e+04,
        7.264200e+02,  9.996080e+03,  4.067900e+02,  2.341800e+02,
        1.263570e+03,  4.865880e+03,  2.646580e+03,  2.624200e+02])

In [47]:
df_pr['unit_price'].isna().sum()

np.int64(16)

In [55]:
df_pr[df_pr['unit_price'].isna()]

,product_id,product_name,category,sub_category,unit_price,unit_cost,seller_id,quality_score
52,P0183,Fashion Item 183,Fashion,Fashion - Type 4,NaN,160.85,S0052,4.68
58,P0091,Beauty Item 91,Beauty,Beauty - Type 1,NaN,180.92,S0065,2.56
65,P0557,Electronics Item 557,Electronic,Electronics - Type 3,NaN,2409.45,S0117,3.18
70,P0453,Electronics Item 453,Electronic,Electronics - Type 4,NaN,1627.03,S0030,4.43
127,P0432,Beauty Item 432,Beauty,Beauty - Type 1,NaN,1051.51,S0131,4.77
169,P0506,Beauty Item 506,Beauty,Beauty - Type 2,NaN,87.65,S0063,4.13
189,P0292,Fashion Item 292,Fashion,Fashion - Type 3,NaN,1256.96,S0122,3.62
194,P0416,Sports Item 416,Sports,Sports - Type 1,NaN,182.51,S0052,2.69
243,P0363,Books Item 363,Books,Books - Type 4,NaN,168.73,S0168,4.84
277,P0245,Fashion Item 245,Fashion,Fashion - Type 3,NaN,159308.00,S0102,4.93
284,P0522,Home & Kitchen Item 522,Home & Kitchen,Home & Kitchen - Type 1,NaN,939.32,S0096,3.82
303,P0090,Fashion Item 90,Fashion,Fashion - Type 3,NaN,1791.78,S0186,4.41
309,P0340,Fashion Item 340,Fashion,Fashion - Type 2,NaN,570.54,S0119,2.51
440,P0413,Beauty Item 413,Beauty,Beauty - Type 3,NaN,1708.46,S0074,4.32
575,P0072,Books Item 72,Books,Books - Type 3,NaN,115.91,S0056,4.68
588,P0142,Toys Item 142,Toys,Toys - Type 1,NaN,1114.84,S0153,4.31

In [59]:
df_pr.groupby('category')['unit_price'].unique()

category
Beauty            [343.29, 302.02, 1593.62, 249.9, 644.47, 767.1...
Books             [242.25, 192.29, 568.75, 425.16, 559.7, 207.92...
Electronic        [4026.16, 15480.42, 1725.65, 54951.84, 42155.6...
Electronics       [2577.31, 19995.95, 2814.0, 13057.39, 11791.62...
Fashion           [1291.23, 3164.18, 433.37, 4305.21, 347.57, 21...
Grocery           [205.69, 756.92, 119.08, 64.86, 114.19, 155.35...
Home & Kitchen    [6204.23, 3153.56, 4522.22, 1938.87, 6524.28, ...
Sports            [4814.5, 3726.75, 1076.92, 3495.83, 3130.34, 4...
Toys              [734.2, 466.74, 2104.78, -2525.45, 1888.84, 36...
Name: unit_price, dtype: object

In [64]:
df_pr.columns

Index(['product_id', 'product_name', 'category', 'sub_category', 'unit_price',
       'unit_cost', 'seller_id', 'quality_score'],
      dtype='str')

In [68]:
df_pr[df_pr['product_name'] == 'Fashion Item 183'][['product_name', 'unit_price', 'unit_cost']]

        product_name  unit_price  unit_cost
52  Fashion Item 183         NaN     160.85

In [69]:
# i think we can/t fill these values. so leave them as they are and fill with null

In [70]:
# but we can refer order table for this.

In [73]:
df_pr.head(10)

,product_id,product_name,category,sub_category,unit_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64
5,P0384,Fashion Item 384,Fashion,Fashion - Type 4,3164.18,1456.80,S0056,2.70
6,P0174,Grocery Item 174,Grocery,Grocery - Type 1,205.69,177.12,S0048,3.98
7,P0492,Home & Kitchen Item 492,Home & Kitchen,Home & Kitchen - Type 2,3153.56,2262.12,S0120,4.19
8,P0435,Fashion Item 435,Fashion,Fashion - Type 2,433.37,189.30,S0082,4.14
9,P0395,Beauty Item 395,Beauty,Beauty - Type 2,343.29,244.72,S0134,3.57

In [77]:
# renaming unit_price to list_price
df_pr.rename(columns = {'unit_price':'list_price'}, inplace = True)

In [78]:
df_pr.head()

,product_id,product_name,category,sub_category,list_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64

In [71]:
df_o = pd.read_csv('orders_clean.csv')

In [72]:
df_o.columns

Index(['order_id', 'customer_id', 'order_date', 'product_id', 'seller_id',
       'quantity', 'list_price', 'discount_pct', 'sales_amount', 'cost_amount',
       'profit', 'order_status', 'shipping_days'],
      dtype='str')

In [86]:
lookup = (
    df_o[['product_id', 'seller_id', 'list_price']]
    .drop_duplicates()
    .set_index(['product_id', 'seller_id'])['list_price']
)

preview = df_pr[df_pr['list_price'].isna()].copy()

preview['list_price_from_orders'] = preview.set_index(
    ['product_id', 'seller_id']
).index.map(lookup)

preview[['product_id', 'seller_id', 'list_price', 'list_price_from_orders']]

    product_id seller_id  list_price  list_price_from_orders
52       P0183     S0052         NaN                  303.32
58       P0091     S0065         NaN                  381.37
65       P0557     S0117         NaN                 3234.53
70       P0453     S0030         NaN                 2168.57
127      P0432     S0131         NaN                 1645.88
169      P0506     S0063         NaN                  188.31
189      P0292     S0122         NaN                 2142.58
194      P0416     S0052         NaN                  305.18
243      P0363     S0168         NaN                  248.79
277      P0245     S0102         NaN                 2672.15
284      P0522     S0096         NaN                 1435.38
303      P0090     S0186         NaN                 4353.60
309      P0340     S0119         NaN                 1228.03
440      P0413     S0074         NaN                 2516.43
575      P0072     S0056         NaN                  153.74
588      P0142     S0153         NaN                 1541.70

In [87]:
preview[
    preview['list_price_from_orders'].notna()
][['product_id', 'seller_id', 'list_price_from_orders']]

    product_id seller_id  list_price_from_orders
52       P0183     S0052                  303.32
58       P0091     S0065                  381.37
65       P0557     S0117                 3234.53
70       P0453     S0030                 2168.57
127      P0432     S0131                 1645.88
169      P0506     S0063                  188.31
189      P0292     S0122                 2142.58
194      P0416     S0052                  305.18
243      P0363     S0168                  248.79
277      P0245     S0102                 2672.15
284      P0522     S0096                 1435.38
303      P0090     S0186                 4353.60
309      P0340     S0119                 1228.03
440      P0413     S0074                 2516.43
575      P0072     S0056                  153.74
588      P0142     S0153                 1541.70

In [89]:
df_pr['list_price'] = df_pr['list_price'].fillna(
    pd.Series(
        df_pr.set_index(['product_id', 'seller_id'])
             .index.map(lookup),
        index=df_pr.index
    )
)

In [90]:
fill_values = pd.Series(
    df_pr.set_index(['product_id', 'seller_id'])
         .index.map(lookup),
    index=df_pr.index
)

df_pr[df_pr['list_price'].isna()][
    ['product_id', 'seller_id', 'list_price']
].assign(new_price=fill_values[df_pr['list_price'].isna()])

Empty DataFrame
Columns: [product_id, seller_id, list_price, new_price]
Index: []

In [91]:
df_pr['list_price'] = df_pr['list_price'].fillna(fill_values)

In [95]:
df_pr.isna().sum()

product_id       0
product_name     0
category         0
sub_category     0
list_price       0
unit_cost        0
seller_id        0
quality_score    0
dtype: int64

In [96]:
df_pr.info()

<class 'pandas.DataFrame'>
Index: 600 entries, 0 to 611
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     600 non-null    str
 1   product_name   600 non-null    str
 2   category       600 non-null    str
 3   sub_category   600 non-null    str
 4   list_price     600 non-null    float64
 5   unit_cost      600 non-null    float64
 6   seller_id      600 non-null    str
 7   quality_score  600 non-null    float64
dtypes: float64(3), str(5)
memory usage: 89.0 KB

In [98]:
df_pr['quality_score'].unique()

array([3.3 , 3.08, 2.64, 4.61, 3.64, 2.7 , 3.98, 4.19, 4.14, 3.57, 4.33,
       3.56, 3.48, 3.9 , 4.67, 3.45, 2.53, 3.73, 3.92, 3.28, 4.65, 4.87,
       4.51, 4.86, 4.23, 3.17, 4.58, 4.56, 3.58, 3.87, 2.98, 4.68, 4.29,
       4.36, 4.44, 3.46, 4.12, 2.85, 4.74, 3.95, 2.55, 2.56, 3.  , 3.77,
       3.52, 3.03, 2.9 , 3.96, 4.06, 3.5 , 3.4 , 2.5 , 4.04, 2.72, 3.18,
       3.19, 3.11, 4.43, 4.16, 2.86, 4.41, 2.84, 4.81, 3.43, 3.86, 3.59,
       4.66, 2.81, 3.24, 2.87, 4.96, 4.13, 4.09, 2.76, 3.51, 4.62, 2.91,
       4.05, 3.21, 3.7 , 4.83, 2.92, 4.71, 3.76, 2.6 , 3.22, 3.83, 2.83,
       2.89, 2.95, 4.15, 2.57, 2.77, 4.77, 3.82, 2.67, 4.79, 3.07, 3.71,
       3.39, 2.62, 4.5 , 4.75, 4.24, 3.72, 2.71, 4.46, 3.84, 4.91, 3.25,
       4.8 , 3.16, 4.54, 4.6 , 4.84, 4.92, 2.61, 3.15, 2.66, 3.14, 3.88,
       5.  , 4.82, 3.2 , 4.99, 4.53, 2.88, 3.62, 4.7 , 4.93, 4.38, 2.69,
       3.68, 4.73, 3.79, 4.03, 4.47, 3.26, 3.33, 4.39, 4.48, 3.27, 4.97,
       4.26, 3.66, 4.01, 3.05, 4.28, 3.99, 4.57, 4.08, 4.11, 4.49, 4.2 ,
       4.21, 3.36, 3.42, 4.72, 3.01, 4.78, 4.9 , 4.22, 4.32, 4.31, 3.35,
       4.45, 2.93, 3.8 , 3.09, 4.42, 3.93, 2.51, 3.02, 4.95, 4.76, 4.35,
       3.06, 3.32, 3.6 , 3.34, 3.04, 3.85, 2.54, 4.1 , 4.52, 2.8 , 4.3 ,
       4.4 , 4.02, 2.78, 4.94, 3.38, 2.65, 2.99, 3.44, 4.34, 4.85, 4.18,
       2.63, 3.63, 3.54, 3.89, 4.69, 3.29, 4.07, 2.73, 2.96, 3.12, 2.74,
       3.31, 2.79, 3.91, 3.69, 4.25, 4.63, 3.67, 3.37, 3.97, 4.55, 2.59,
       2.97, 3.55, 3.23, 3.78, 2.52, 4.  , 2.68, 2.82, 3.1 , 4.27, 4.37,
       4.89])

In [100]:
df_pr.duplicated().sum()

np.int64(0)

In [101]:
df_pr.head()

,product_id,product_name,category,sub_category,list_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64

In [103]:
df_pr['category'].unique()

<ArrowStringArray>
[         'Books',     'Electronic',         'Sports', 'Home & Kitchen',
        'Fashion',        'Grocery',         'Beauty',    'Electronics',
           'Toys']
Length: 9, dtype: str

In [105]:
df_pr.dtypes

product_id           str
product_name         str
category             str
sub_category         str
list_price       float64
unit_cost        float64
seller_id            str
quality_score    float64
dtype: object

In [106]:
df_pr.head()

,product_id,product_name,category,sub_category,list_price,unit_cost,seller_id,quality_score
0,P0494,Books Item 494,Books,Books - Type 2,242.25,159.91,S0194,3.30
1,P0473,Electronics Item 473,Electronic,Electronics - Type 3,4026.16,3034.04,S0131,3.08
2,P0108,Sports Item 108,Sports,Sports - Type 2,4814.50,3196.44,S0093,2.64
3,P0559,Home & Kitchen Item 559,Home & Kitchen,Home & Kitchen - Type 2,6204.23,3917.85,S0021,4.61
4,P0536,Fashion Item 536,Fashion,Fashion - Type 1,1291.23,874.37,S0123,3.64

In [108]:
df_pr.to_csv('products_clean.csv', index = False)